### ISSUE TITLE
Error with view OpenAPI

### ISSUE THREAD

**Issue by xander1234** [restcase/apibldr#1]
The new deploy have a fail,  when you create a resource type "OpenApi" and then you make click en "source" the system put the view in modo AsyncAPI and is imposible return to view "OpenAPI". If you copy and paste some definition en YAML o JSON the view return to AsyncAPI

**Comment by MikeBenza** [comment]
I encountered this two days ago, too.

**Comment by danielgel** [comment]
@xander1234 @MikeBenza , thanks for the info.
I'll take a look

**Comment by danielgel** [comment]
There was a big issue on our side.
I'm uploading an older version of ApiBldr so that you could use it while we work on resolving the issues on our side.

Once everything is fixed a newer version will be deployed.

**Comment by danielgel** [comment]
@xander1234  @MikeBenza , an older version of ApiBldr has been deployed.
You can use it while we resolve the issue.

**Comment by xander1234** [comment]
thanks a lot, your application is very useful and awesome, always I recommend it.

**Comment by danielgel** [comment]
@xander1234  @MikeBenza , I'm sorry for the long wait.
We've addressed a lot of issues and the application looks and feels more stable.

We're releasing a new build of the designer in the next hour 🕺 
If you still get any errors/issues please post them in this repo so that we could address them properly.

Thanks a lot! 😄
