### ISSUE TITLE
Issue with references

### ISSUE THREAD

**Issue by esunder** [restcase/apibldr#2]
It seems like many features around schema references just dont work properly. Is this a known defect?

One example:
Create a parameter component for a petId path parameter and try to reference it in a simple GET /pets/{petId}. The json that is generated is just not correct.

Another example was with the response bodies and referencing schemas.

Is this project open source?

**Comment by danielgel** [comment]
Hi @esunder , sorry for the late response.

So first of all, thanks for the bug description! We've fixed it and releasing a new version of the designer with a lot of fixes and a shiny new look (hope you'll like it 🙏) 

Right now this project is not open-source. We would like it to be, but unfortunately, right now it is not possible
This repo was created so that there would be a place where bugs/issues could be documented and addressed.

Thanks again for the heads up! 😄
